CREATE DATABASE BeerCatalog;
GO
USE BeerCatalog;
GO
CREATE SCHEMA Beer;
GO
CREATE SCHEMA Method;
GO
CREATE SCHEMA Ingredients;
GO;
CREATE TABLE Ingredients.Hops (
Id UNIQUEIDENTIFIER PRIMARY KEY,
NAME NVARCHAR(20) NOT NULL
);
GO
CREATE TABLE Ingredients.Malts (
Id UNIQUEIDENTIFIER PRIMARY KEY,
NAME NVARCHAR(20) NOT NULL
);
GO
CREATE TABLE Ingredients.Yeasts (
Id UNIQUEIDENTIFIER PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE Ingredients.WhenToAdd (
Id INT PRIMARY KEY IDENTITY,
WhenToAdd NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE Ingredients.HopAttribute (
Id INT PRIMARY KEY IDENTITY,
HopAttribute NVARCHAR(30) NOT NULL
);
GO
INSERT INTO Ingredients.WhenToAdd VALUES (N'start'),(N'middle'),(N'end');
INSERT INTO Ingredients.HopAttribute VALUES (N'bitter'),(N'flavour'),(N'aroma');
GO
CREATE TABLE Beer.Beers (
Id UNIQUEIDENTIFIER PRIMARY KEY,
Name NVARCHAR(30) UNIQUE NOT NULL,
Tagline NVARCHAR(30) NOT NULL,
Description NVARCHAR(500) NOT NULL,
ImageUrl NVARCHAR(500) NOT NULL,
Abv FLOAT NOT NULL CHECK (Abv > 0),
Ibu FLOAT NOT NULL CHECK (Ibu > 0),
Ebc FLOAT NOT NULL CHECK (Ebc > 0),
BrewersTips NVARCHAR(200) NOT NULL,
YeastId UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(YeastId) REFERENCES Ingredients.Yeasts(Id)
);
GO
CREATE TABLE Beer.HopIngredients (
BeerId UNIQUEIDENTIFIER NOT NULL,
HopId UNIQUEIDENTIFIER NOT NULL,
Value FLOAT NOT NULL CHECK (Value > 0),
WhenToAddId INT NOT NULL,
AttributeId INT NOT NULL,
PRIMARY KEY(BeerId, HopId),
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id),
FOREIGN KEY(HopId) REFERENCES Ingredients.Hops(Id),
FOREIGN KEY(WhenToAddId) REFERENCES Ingredients.WhenToAdd(Id),
FOREIGN KEY(AttributeId) REFERENCES Ingredients.HopAttribute(Id)
);
GO
CREATE TABLE Beer.MaltIngredients (
BeerId UNIQUEIDENTIFIER NOT NULL,
MaltId UNIQUEIDENTIFIER NOT NULL,
Value FLOAT NOT NULL CHECK (Value > 0),
PRIMARY KEY(BeerId, MaltId),
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id),
FOREIGN KEY(MaltId) REFERENCES Ingredients.Malts(Id),
);
GO
CREATE TABLE Method.MashTemp (
Id UNIQUEIDENTIFIER PRIMARY KEY,
Value INT NOT NULL CHECK (Value > 0),
Duration INT NOT NULL CHECK (Value > 0),
BeerId UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id)
);
GO
CREATE TABLE Method.Fermentation (
Id UNIQUEIDENTIFIER PRIMARY KEY,
VALUE INT NOT NULL CHECK (Value > 0),
BeerId UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id)
);
GO
CREATE TABLE Method.Twists (
Id UNIQUEIDENTIFIER PRIMARY KEY,
Name NVARCHAR(200) NOT NULL,
BeerId UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id)
);
GO
CREATE TABLE Beer.Food (
Id UNIQUEIDENTIFIER PRIMARY KEY,
Name NVARCHAR(100) NOT NULL
);
GO
CREATE TABLE Beer.FoodPairing (
BeerId UNIQUEIDENTIFIER,
FoodId UNIQUEIDENTIFIER,
PRIMARY KEY(BeerId, FoodId),
FOREIGN KEY(BeerId) REFERENCES Beer.Beers(Id),
FOREIGN KEY(FoodId) REFERENCES Beer.Food(Id)
);
GO