export const GET_BEERS_REQUEST = "GET_BEERS_REQUEST";
export const GET_BEERS_SUCCESS = "GET_BEERS_SUCCESS";
export const GET_BEERS_FAILED = "GET_BEERS_FAILED";

export const SET_WAS_SEARCH_PERFORMED = "SET_WAS_SEARCH_PERFORMED";

export const GET_BEER_BY_ID_REQUEST = "GET_BEER_BY_ID_REQUEST";
export const GET_BEER_BY_ID_SUCCESS = "GET_BEER_BY_ID_SUCCESS";

export const CLEAR_FLAGS = "CLEAR_FLAGS";
export const RESET_BEERS = "RESET_BEERS";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CONFIRM_EMAIL_REQUEST = "CONFIRM_EMAIL_REQUEST";
export const CONFIRM_EMAIL_SUCCESS = "CONFIRM_EMAIL_SUCCESS";
export const CONFIRM_EMAIL_FAILED = "CONFIRM_EMAIL_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_FAILED = "CHECK_EMAIL_FAILED";

export const CHECK_USERNAME_REQUEST = "CHECK_USERNAME_REQUEST";
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS";
export const CHECK_USERNAME_FAILED = "CHECK_USERNAME_FAILED";

export const START_VALIDATING = "START_VALIDATING";

export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";

export const GET_FAVORITES_REQUEST = "GET_FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_FAILED = "GET_FAVORITES_FAILED";

export const ADD_FAVORITE_REQUEST = "ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILED = "ADD_FAVORITE_FAILED";

export const REMOVE_FAVORITE_REQUEST = "REMOVE_FAVORITE_REQUEST";
export const REMOVE_FAVORITE_SUCCESS = "REMOVE_FAVORITE_SUCCESS";
export const REMOVE_FAVORITE_FAILED = "REMOVE_FAVORITE_FAILED";

export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";