export const GET_BEERS_REQUEST = "GET_BEERS_REQUEST";
export const GET_BEERS_SUCCESS = "GET_BEERS_SUCCESS";
export const GET_BEERS_FAILED = "GET_BEERS_FAILED";
export const SEARCH_BEERS_REQUEST = "SEARCH_BEERS_REQUEST";
export const SEARCH_BEERS_SUCCESS = "SEARCH_BEERS_SUCCESS";
export const SEARCH_BEERS_FAILED = "SEARCH_BEERS_FAILED";
