export const GET_BEERS_REQUEST = "GET_BEERS_REQUEST";
export const GET_BEERS_SUCCESS = "GET_BEERS_SUCCESS";
export const GET_BEERS_FAILED = "GET_BEERS_FAILED";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const SET_WAS_SEARCH_PERFORMED = "SET_WAS_SEARCH_PERFORMED";
export const INCREMENT_PAGE = "INCREMENT_PAGE";